### PR TITLE
Improved cart.html #7

### PR DESCRIPTION
**Pull request by Manish-Syal123**
1. Improved  
Screenshot 2022-10-25 172752

2. Added media query ,so that in small screen the name of the product will not appear.
 ```
.cart-info p{
        display: none;
    }
```
Screenshot 2022-10-25 173023

### CODE REVIEW

**Comment by Manish-Syal123** [comment]
Please don't forget to add "hacktoberfest-accepted" tag .

**Comment by Manish-Syal123** [comment]
That's a loot

**Comment by Manish-Syal123** [comment]
Lot 😅

**Comment by abhijit49** [comment]
Enjoy yourself🎆
Consider this a Diwali gift from me

**Comment by Manish-Syal123** [comment]
😊🙂

**Pull request merged**
