### PR TITLE
Improve cart page for issue #17

### PR DESCRIPTION
**Pull request by srijoy-paul**
This PR resolves issue #17

### CODE REVIEW

**Comment by abhijit49** [comment]
@srijoy-paul  not commit into main. Commit into new branch

**Comment by srijoy-paul** [comment]
@abhijit49 In which branch?

**Comment by srijoy-paul** [comment]
Check now, Made a PR from a new branch

**Comment by srijoy-paul** [comment]
@abhijit49  Please, Check the new PR #22 and merge it, so that I can start working on the next issue.  And close this PR #21

**Pull request merged**
